device: cuda
seed: 3333

model:
  stu_model:
    name: ResNet34U_f
  tea_model:
    name: ResNet34U_f_ExtendDAv2_BiFusion
    dav2_model_name: 'depth-anything/Depth-Anything-V2-Small-hf'
    use_cnn_residual: true
    bifusion_drop: 0.05
  num_channels_output: 1
data:
  root: ../polypdepth_dataset/
  dataset: kvasir_SEG
  data2_dir: TrainDataset
  require_depth: False
  image_dirname: images
  mask_dirname: masks
  depth_dirname:
  json_filename: datalist_info/official/kvasir_SEG_seed_42.json
  label_mode: percentage
  labeled_perc: 10
  labeled_bs: 2
  batch_size: 4
  shuffle: false
  num_workers: 0
  val_split_perc: 0
  test:
    resize_width: 320
    resize_height: 320
    dataset_root: ../polypdepth_dataset/TestDataset/Kvasir
    dataset_name: 
    image_dirname: images
    mask_dirname: masks
    depth_dirname:
    batch_size: 1

nEpoch: 300

optimizer:
  lr: 0.01
  weight_decay: 0.0001
  momentum: 0.9

tea_optimizer:
  lr: 0.01
  weight_decay: 0.0001
  momentum: 0.9

scheduler:
  eta_min: 1.0e-5

Trainer:
  rampup_unit: 'iter'
  consistency_rampup: 5000
  ema_decay: 0.999
  consistency: 2.0
  teacher_reliable_threshold: 0.75
  student_reliable_threshold: 0.85
  depth_learn_from_stu_weight: 0.3

Hook:
  MeanTeacherEvalHook:
    eval_every_epoch: 2
  ExtendMLFlowLoggerHook:
    should_use: True
    plot_every_epoch: 1
    dagshub_repo_owner: 'AkiyaNguyen'
    dagshub_repo_name: 'polyp_segmentation'
    experiment_name: 'bi_fusion_dav2_mt_train'
    dir_save_plot: 'plots'
    logging_fields:
      - '*loss*'
      - '*lr*'
      - '*weight*'
      - '*Dice*'
      - '*IoU*'
      - '*ACC_overall*'
    local_dir_save_ckpt: 'ckpt'
    dagshub_dir_save_ckpt: 'ckpt'
    max_save_epoch_interval: 50
    criteria: test_stu_Dice
    log_every_epoch: 1
    dagshub_destination_src_file: 'src_file'
    list_src_dir_files: ['utils', 'test', 'models', 'data', 'logs', 'BiFusion_DEMT_DAv2.py']
    dagshub_meta_dir: 'meta'
    run_name:
    meta_info:
      kaggle_run_link:
      dataset_link: https://www.kaggle.com/datasets/akiyanguyen/polypdataset
      description: 'Mean Teacher with DAv2 + BiFusion'

score_criteria: test_stu_Dice

hyperparameter_sweep:
  Trainer/depth_learn_from_stu_weight:
    method: suggest_categorical
    params:
      name: depth_learn_from_stu_weight
      choices: [0.2, 0.4, 0.5]